### ISSUE TITLE
水平垂直居中的几种方式

### ISSUE THREAD

**Issue by zhuziqingdemao** [zhuziqingdemao/Blog#6]
## 垂直居中

**flex布局**  垂直都在用的解决方案

**position: absolute**

```css
.parent{
	position: relative;
}
// 1.tranform
.child {
    position: absolute;
   	top: 50%;
    left: 50%;
    transform:translate(-50%,-50%)
}
// 2.left/right: 0
.child {
    position: absolute;
   	top: 50%;
    height: 高度;
    margion-top: -0.5 * 高度;
}
// 3.top/bottom:0
.child {
    position: absolute;
   	top: 0;
    bottom: 0;
    margion:auto 0;
}
```

**已知子容器宽高的情况下**

```css
.c {
  width: 300px;
  height: 300px;
  margion: 0 auto;  
}
```

**行内元素**

```css
.c {
	line-height: height;
}
```

### 水平居中

**行内元素**

```css
.c {
	text-align: center;
}
```

**绝对定位**

```css
// 1) tansform
.c {
    position: abslute;
    left: 50%:
    transform: translate(-50%, 0);
}
// 2) 已知宽度
.c {
    position: abslute;
    left: 50%:
    margion-left: -0.5* width;
}
// 3 left/right:0
.c {
    position: abslute;
    width: 300px;
    left: 0;
    right: 0;
    margion:0 auto;
}
```
